/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import clases.Conexion;
import clases.Diseño;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author mimel
 */
public class Ajustes extends javax.swing.JFrame {

    /**
     * Creates new form Ajustes
     */
    public Ajustes() {
        initComponents();
        
        Diseño d = new Diseño();
        d.colocarLogo(this);
        Diseño.diseñoFrame(this);
        this.setTitle("Partidas de Ajustes");
        this.setLocationRelativeTo(null);
        
        //Tabla de Cuentas
        inicializarColumnas();
        actualizarTabla(tbCuentas2);
    }
    
    Conexion connect = new Conexion();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbCuentas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCuentas1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCuentas2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cbAjustes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();

        tbCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(tbCuentas);

        tbCuentas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre"
            }
        ));
        jScrollPane2.setViewportView(tbCuentas1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Ajustes");

        jLabel3.setText("Código Transacción:");

        tbCuentas2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre"
            }
        ));
        tbCuentas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCuentas2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbCuentas2);

        jLabel4.setText("Tipo de Ajuste: ");

        cbAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAjustesActionPerformed(evt);
            }
        });

        jLabel5.setText("Monto:                       $");

        txtMonto.setText("  ");
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        jLabel6.setText("Razón del Ajuste:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane4.setViewportView(txtDescripcion);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void tbCuentas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCuentas2MouseClicked
        int filaSeleccionada = tbCuentas2.getSelectedRow();

        if (filaSeleccionada != -1) {
            int idCombinado = obtenerIdCombinado((int) tbCuentas2.getValueAt(filaSeleccionada, 0));

            actualizarComboBoxTipoAjuste(idCombinado);
        }
    }//GEN-LAST:event_tbCuentas2MouseClicked


    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Menu m = new Menu();
        m.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed


    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
          if (txtDescripcion.getText().isEmpty() || txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int filaSeleccionada = tbCuentas2.getSelectedRow();
        int idCuenta = (int) tbCuentas2.getValueAt(filaSeleccionada, 0);

        String nombreCuenta = cbAjustes.getSelectedItem().toString();
        int valorId = Integer.parseInt(txtCodigo.getText());
        LocalDate fechaActual = LocalDate.now();
        java.sql.Date fechaSQL = java.sql.Date.valueOf(fechaActual);
        String valorDescripcion = "<Ajuste> "+txtDescripcion.getText();
        double valorMonto = Double.parseDouble(txtMonto.getText());
        double debeTrans = 0;
        double haberTrans = 0;



        // Determinar si el monto se registra en "debe_trans" o "haber_trans" según la naturaleza de la cuenta
        if (esCuentaIngresos(nombreCuenta) || esCuentaActivo(nombreCuenta)) {
            haberTrans = valorMonto;
        } else if (esCuentaGastos(nombreCuenta)) {
            debeTrans = valorMonto;
        }

        // Guardar los datos en la base de datos
        try {
            connect.conectar();
            String sentencia = "INSERT INTO transaccion (idtransaccion, idcuenta, nombre_cuenta, descripcion, fecha_transaccion, debe_trans, haber_trans) VALUES (?, ?, ?, ?, ?, ?, ?)";
            try (PreparedStatement ps = this.connect.getConexion().prepareStatement(sentencia)) {
                ps.setInt(1, valorId);
                ps.setInt(2, idCuenta);
                ps.setString(3, nombreCuenta);
                ps.setString(4, valorDescripcion);
                ps.setDate(5, fechaSQL);
                ps.setDouble(6, debeTrans);
                ps.setDouble(7, haberTrans);

                ps.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Datos guardados correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            txtCodigo.setText("");
            txtDescripcion.setText("");
            txtMonto.setText("");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        actualizarTabla(tbCuentas2);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAjustesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAjustesActionPerformed

    private boolean esCuentaIngresos(String nombreCuenta) {
        return nombreCuenta.equals("Proyectos de software personalizado") || nombreCuenta.equals("Mantenimiento y soporte");
    }

    private boolean esCuentaGastos(String nombreCuenta) {
        return nombreCuenta.equals("Gastos de personal") || nombreCuenta.equals("Gastos de administracion") || nombreCuenta.equals("Gastos de Oficina");
    }

    private boolean esCuentaActivo(String nombreCuenta) {
        return nombreCuenta.equals("Local") || nombreCuenta.equals("Mobiliario y equipo");
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajustes().setVisible(true);
            }
        });
    }

    
    private void inicializarColumnas() {
        TableColumnModel tColumnModel = new DefaultTableColumnModel();
        for (int i = 0; i < 2; i++) {
            TableColumn col = new TableColumn(i);
            switch (i) {
                case 0:
                    col.setHeaderValue("Código");
                    break;
                case 1:
                    col.setHeaderValue("Nombre de cuenta");
                    break;
            }
            tColumnModel.addColumn(col);
        }
        this.tbCuentas.setColumnModel(tColumnModel);
    }
    
    


    
    private int obtenerIdCombinado(int idCuenta) {
        try {
            String sentencia = "SELECT idtipo, idclasificacion FROM cuenta WHERE idcuenta = ?"; // Reemplaza con el nombre de tu tabla

            PreparedStatement ps;
            ps = this.connect.getConexion().prepareCall(sentencia);
            
            // Se establece el valor del parámetro en la consulta
            ps.setInt(1, idCuenta);
            ResultSet resultado = ps.executeQuery();

            if (resultado.next()) {
                // Obtiene los valores de idtipo e idclasificacion
                int idTipo = resultado.getInt("idtipo");
                int idClasificacion = resultado.getInt("idclasificacion");

                // Combina los valores de idtipo e idclasificacion en una variable
                int idCombinado = idTipo * 100 + idClasificacion;
                System.out.println(String.valueOf(idCombinado));
                return idCombinado;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return -1; // Valor por defecto en caso de error o si no se encuentra la cuenta
    }
    
    
    public void actualizarTabla(JTable tabla){
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0); // Limpia la tabla
        
        try {
            String sentencia = "SELECT idcuenta, nombre_cuenta FROM cuenta ORDER BY idcuenta";
            PreparedStatement sentencia1;
            sentencia1 = null;
            sentencia1 = this.connect.getConexion().prepareCall(sentencia);
            ResultSet rs = sentencia1.executeQuery();
            while (rs.next()) {
                int idcuenta = rs.getInt("idcuenta");
                String nombre = rs.getString("nombre_cuenta");
                modelo.addRow(new Object[]{idcuenta, nombre});
            }
            rs.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
   private void actualizarComboBoxTipoAjuste(int idCombinado) {
        // Borra las opciones actuales del ComboBox de tipo de ajuste
        cbAjustes.removeAllItems();

        // Llena el ComboBox con las opciones basadas en el idCombinado de la cuenta
        switch (idCombinado) {
            case 441:
                // Devengación de Ingresos (Ingresos por Servicios)
                cbAjustes.addItem("Proyectos de software personalizado");
                cbAjustes.addItem("Mantenimiento y soporte");
                break;
            case 551:
                // Gastos Devengados
                cbAjustes.addItem("Gastos de personal");
                cbAjustes.addItem("Gastos de administracion");
                cbAjustes.addItem("Gastos de oficina");
                break;
            case 112:
                // Depreciación de Activos
                cbAjustes.addItem("Local");
                cbAjustes.addItem("Mobiliario y equipo");
                break;
            default:
                break;
        }
  
        // Habilitar/deshabilitar el ComboBox según la presencia de opciones
        cbAjustes.setEnabled(cbAjustes.getItemCount() > 0);
    }



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbAjustes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbCuentas;
    private javax.swing.JTable tbCuentas1;
    private javax.swing.JTable tbCuentas2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
